---

 - name: Create alarm SNS topic
   sns_topic:
    name: "alarms"
    state: present
    region: "{{REGION}}"
    aws_access_key: "{{AccessKey}}"
    aws_secret_key: "{{SecretKey}}"

    display_name: "alarm SNS topic"
    subscriptions:
      - endpoint: "{{ENDPOINT}]"
        protocol: "email"

   register: snsar

 - name: "debug the ARN"
   debug:
       var: snsar.sns_arn

 - name: "create alarm"
   ec2_metric_alarm:
          state: present
          region: "{{REGION}}"
          aws_access_key: "{{AccessKey}}"
          aws_secret_key: "{{SecretKey}}"
          name: "diskpace low"
          metric: "DiskSpaceUtilization"
          namespace: "System/Linux"
          statistic: "Average"
          comparison: ">="
          threshold: 80
          period: 300
          evaluation_periods: 3
          unit: "Percent"
          description: "This will alarm when disk usage exceeded or equla 80%"
          alarm_actions: "{{snsar.sns_arn}}"

    
